### PROJECT : Unstructured Text Data Cleaning

In [4]:
#import require library
import pandas as pd

In [5]:
#1. Load Row Data
df=pd.read_csv(r"C:\Users\Sneha\Downloads\houses.txt",on_bad_lines="skip",header=None,skiprows=[0,1,2])
df.head(20)

,0,1,2
0,...',Wiley,1980. N.B. Various transformations are used...
1,pages 244-261 of the latter.,NaN,NaN
2,Variables in order:,NaN,NaN
3,CRIM per capita crime rate by town,NaN,NaN
4,ZN proportion of residential land zoned...,000 sq.ft.,NaN
5,INDUS proportion of non-retail business ac...,NaN,NaN
6,CHAS Charles River dummy variable (= 1 if...,NaN,NaN
7,NOX nitric oxides concentration (parts p...,NaN,NaN
8,RM average number of rooms per dwelling,NaN,NaN
9,AGE proportion of owner-occupied units b...,NaN,NaN
10,DIS weighted distances to five Boston em...,NaN,NaN
11,RAD index of accessibility to radial hig...,NaN,NaN
12,TAX full-value property-tax rate per $10,000,NaN
13,PTRATIO pupil-teacher ratio by town,NaN,NaN
14,B 1000(Bk - 0.63)^2 where Bk is the pr...,NaN,NaN
15,LSTAT % lower status of the population,NaN,NaN
16,MEDV Median value of owner-occupied homes...,NaN,NaN
17,0.00632 18.00 2.310 0 0.5380 6.5750 65...,NaN,NaN
18,396.90 4.98 24.00,NaN,NaN
19,0.02731 0.00 7.070 0 0.4690 6.4210 78...,NaN,NaN

### Extract header section

In [6]:
# Extract column names (header section)
header_row=df.iloc[3:17]
header_row

                                                    0           1    2
3              CRIM     per capita crime rate by town         NaN  NaN
4    ZN       proportion of residential land zoned...  000 sq.ft.  NaN
5    INDUS    proportion of non-retail business ac...         NaN  NaN
6    CHAS     Charles River dummy variable (= 1 if...         NaN  NaN
7    NOX      nitric oxides concentration (parts p...         NaN  NaN
8       RM       average number of rooms per dwelling         NaN  NaN
9    AGE      proportion of owner-occupied units b...         NaN  NaN
10   DIS      weighted distances to five Boston em...         NaN  NaN
11   RAD      index of accessibility to radial hig...         NaN  NaN
12      TAX      full-value property-tax rate per $10         000  NaN
13               PTRATIO  pupil-teacher ratio by town         NaN  NaN
14   B        1000(Bk - 0.63)^2 where Bk is the pr...         NaN  NaN
15          LSTAT    % lower status of the population         NaN  NaN
16   MEDV     Median value of owner-occupied homes...         NaN  NaN

In [8]:
header=header_row[0].str.split(" ",expand=True)[1]
header

3        CRIM
4          ZN
5       INDUS
6        CHAS
7         NOX
8          RM
9         AGE
10        DIS
11        RAD
12        TAX
13    PTRATIO
14          B
15      LSTAT
16       MEDV
Name: 1, dtype: object

In [9]:
#Extract actual data (after header)
data=df.iloc[17:]
data

                                                      0    1    2
17     0.00632  18.00   2.310  0  0.5380  6.5750  65...  NaN  NaN
18                                 396.90   4.98  24.00  NaN  NaN
19     0.02731   0.00   7.070  0  0.4690  6.4210  78...  NaN  NaN
20                                 396.90   9.14  21.60  NaN  NaN
21     0.02729   0.00   7.070  0  0.4690  7.1850  61...  NaN  NaN
...                                                 ...  ...  ...
1024                               396.90   5.64  23.90  NaN  NaN
1025   0.10959   0.00  11.930  0  0.5730  6.7940  89...  NaN  NaN
1026                               393.45   6.48  22.00  NaN  NaN
1027   0.04741   0.00  11.930  0  0.5730  6.0300  80...  NaN  NaN
1028                               396.90   7.88  11.90  NaN  NaN

[1012 rows x 3 columns]

### Handle Multiple Line Records using iloc (Each Record =2 rows)

In [11]:
data_row1=data.iloc[:1028:2]
data_row1

                                                      0    1    2
17     0.00632  18.00   2.310  0  0.5380  6.5750  65...  NaN  NaN
19     0.02731   0.00   7.070  0  0.4690  6.4210  78...  NaN  NaN
21     0.02729   0.00   7.070  0  0.4690  7.1850  61...  NaN  NaN
23     0.03237   0.00   2.180  0  0.4580  6.9980  45...  NaN  NaN
25     0.06905   0.00   2.180  0  0.4580  7.1470  54...  NaN  NaN
...                                                 ...  ...  ...
1019   0.06263   0.00  11.930  0  0.5730  6.5930  69...  NaN  NaN
1021   0.04527   0.00  11.930  0  0.5730  6.1200  76...  NaN  NaN
1023   0.06076   0.00  11.930  0  0.5730  6.9760  91...  NaN  NaN
1025   0.10959   0.00  11.930  0  0.5730  6.7940  89...  NaN  NaN
1027   0.04741   0.00  11.930  0  0.5730  6.0300  80...  NaN  NaN

[506 rows x 3 columns]

In [12]:
data_1=data_row1[0].str.split("  ",expand=True)# Split Columns using Multiple Spaces
data_1.reset_index(inplace=True)
data_1

,index,0,1,2,3,4,5,6,7,8,9,10
0,17,0.00632,18.00,2.310,0,0.5380,6.5750,65.20,4.0900,1,296.0,15.30
1,19,0.02731,0.00,7.070,0,0.4690,6.4210,78.90,4.9671,2,242.0,17.80
2,21,0.02729,0.00,7.070,0,0.4690,7.1850,61.10,4.9671,2,242.0,17.80
3,23,0.03237,0.00,2.180,0,0.4580,6.9980,45.80,6.0622,3,222.0,18.70
4,25,0.06905,0.00,2.180,0,0.4580,7.1470,54.20,6.0622,3,222.0,18.70
...,...,...,...,...,...,...,...,...,...,...,...,...
501,1019,0.06263,0.00,11.930,0,0.5730,6.5930,69.10,2.4786,1,273.0,21.00
502,1021,0.04527,0.00,11.930,0,0.5730,6.1200,76.70,2.2875,1,273.0,21.00
503,1023,0.06076,0.00,11.930,0,0.5730,6.9760,91.00,2.1675,1,273.0,21.00
504,1025,0.10959,0.00,11.930,0,0.5730,6.7940,89.30,2.3889,1,273.0,21.00
505,1027,0.04741,0.00,11.930,0,0.5730,6.0300,80.80,2.5050,1,273.0,21.00

In [13]:
data_1.drop(columns="index",inplace=True)

In [14]:
data_1

,0,1,2,3,4,5,6,7,8,9,10
0,0.00632,18.00,2.310,0,0.5380,6.5750,65.20,4.0900,1,296.0,15.30
1,0.02731,0.00,7.070,0,0.4690,6.4210,78.90,4.9671,2,242.0,17.80
2,0.02729,0.00,7.070,0,0.4690,7.1850,61.10,4.9671,2,242.0,17.80
3,0.03237,0.00,2.180,0,0.4580,6.9980,45.80,6.0622,3,222.0,18.70
4,0.06905,0.00,2.180,0,0.4580,7.1470,54.20,6.0622,3,222.0,18.70
...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.00,11.930,0,0.5730,6.5930,69.10,2.4786,1,273.0,21.00
502,0.04527,0.00,11.930,0,0.5730,6.1200,76.70,2.2875,1,273.0,21.00
503,0.06076,0.00,11.930,0,0.5730,6.9760,91.00,2.1675,1,273.0,21.00
504,0.10959,0.00,11.930,0,0.5730,6.7940,89.30,2.3889,1,273.0,21.00
505,0.04741,0.00,11.930,0,0.5730,6.0300,80.80,2.5050,1,273.0,21.00

In [15]:
data

                                                      0    1    2
17     0.00632  18.00   2.310  0  0.5380  6.5750  65...  NaN  NaN
18                                 396.90   4.98  24.00  NaN  NaN
19     0.02731   0.00   7.070  0  0.4690  6.4210  78...  NaN  NaN
20                                 396.90   9.14  21.60  NaN  NaN
21     0.02729   0.00   7.070  0  0.4690  7.1850  61...  NaN  NaN
...                                                 ...  ...  ...
1024                               396.90   5.64  23.90  NaN  NaN
1025   0.10959   0.00  11.930  0  0.5730  6.7940  89...  NaN  NaN
1026                               393.45   6.48  22.00  NaN  NaN
1027   0.04741   0.00  11.930  0  0.5730  6.0300  80...  NaN  NaN
1028                               396.90   7.88  11.90  NaN  NaN

[1012 rows x 3 columns]

In [15]:
#Same Process For Data Row 2
data_row2=data.iloc[1:1029:2]
data_row2

                           0    1    2
18      396.90   4.98  24.00  NaN  NaN
20      396.90   9.14  21.60  NaN  NaN
22      392.83   4.03  34.70  NaN  NaN
24      394.63   2.94  33.40  NaN  NaN
26      396.90   5.33  36.20  NaN  NaN
...                      ...  ...  ...
1020    391.99   9.67  22.40  NaN  NaN
1022    396.90   9.08  20.60  NaN  NaN
1024    396.90   5.64  23.90  NaN  NaN
1026    393.45   6.48  22.00  NaN  NaN
1028    396.90   7.88  11.90  NaN  NaN

[506 rows x 3 columns]

In [16]:
data_2=data_row2[0].str.split("  ",expand=True)
data_2

     0        1      2      3     4
18       396.90   4.98  24.00  None
20       396.90   9.14  21.60  None
22       392.83   4.03  34.70  None
24       394.63   2.94  33.40  None
26       396.90   5.33  36.20  None
...  ..     ...    ...    ...   ...
1020     391.99   9.67  22.40  None
1022     396.90   9.08  20.60  None
1024     396.90   5.64  23.90  None
1026     393.45   6.48  22.00  None
1028     396.90   7.88  11.90  None

[506 rows x 5 columns]

In [17]:
data_2.drop(columns=[0,4],inplace=True)#drop unwanted columns
data_2

           1      2      3
18    396.90   4.98  24.00
20    396.90   9.14  21.60
22    392.83   4.03  34.70
24    394.63   2.94  33.40
26    396.90   5.33  36.20
...      ...    ...    ...
1020  391.99   9.67  22.40
1022  396.90   9.08  20.60
1024  396.90   5.64  23.90
1026  393.45   6.48  22.00
1028  396.90   7.88  11.90

[506 rows x 3 columns]

In [18]:
data_2.reset_index(inplace=True)

In [19]:
data_2.drop(columns="index",inplace=True)
data_2

          1      2      3
0    396.90   4.98  24.00
1    396.90   9.14  21.60
2    392.83   4.03  34.70
3    394.63   2.94  33.40
4    396.90   5.33  36.20
..      ...    ...    ...
501  391.99   9.67  22.40
502  396.90   9.08  20.60
503  396.90   5.64  23.90
504  393.45   6.48  22.00
505  396.90   7.88  11.90

[506 rows x 3 columns]

# Combine Both Parts to Form complete Records

In [21]:
finaldata=data_1.join(data_2,rsuffix="data2") #use resuffix for avoiding data overlaping
finaldata.shape

(506, 14)

# assign Column Names

In [24]:
header.shape #hence columns count match

(14,)

In [25]:
finaldata.columns=header

# Final Data Check

In [26]:
finaldata

1,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.00,2.310,0,0.5380,6.5750,65.20,4.0900,1,296.0,15.30,396.90,4.98,24.00
1,0.02731,0.00,7.070,0,0.4690,6.4210,78.90,4.9671,2,242.0,17.80,396.90,9.14,21.60
2,0.02729,0.00,7.070,0,0.4690,7.1850,61.10,4.9671,2,242.0,17.80,392.83,4.03,34.70
3,0.03237,0.00,2.180,0,0.4580,6.9980,45.80,6.0622,3,222.0,18.70,394.63,2.94,33.40
4,0.06905,0.00,2.180,0,0.4580,7.1470,54.20,6.0622,3,222.0,18.70,396.90,5.33,36.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.00,11.930,0,0.5730,6.5930,69.10,2.4786,1,273.0,21.00,391.99,9.67,22.40
502,0.04527,0.00,11.930,0,0.5730,6.1200,76.70,2.2875,1,273.0,21.00,396.90,9.08,20.60
503,0.06076,0.00,11.930,0,0.5730,6.9760,91.00,2.1675,1,273.0,21.00,396.90,5.64,23.90
504,0.10959,0.00,11.930,0,0.5730,6.7940,89.30,2.3889,1,273.0,21.00,393.45,6.48,22.00
505,0.04741,0.00,11.930,0,0.5730,6.0300,80.80,2.5050,1,273.0,21.00,396.90,7.88,11.90

# Save Cleaned data

In [27]:
finaldata.to_csv(r"C:\Users\Sneha\Desktop\Project_folder\cleaned_housing_data.csv", index=False)